"""
User URLs
=========
URL configuration for the users app.

This module defines the URL patterns (routes) that map URLs to views.

URL Routing Workflow:
---------------------
1. Client makes request to: http://localhost:8000/api/users/
2. Django's main urls.py routes to users app
3. This file maps the URL to the appropriate view
4. View processes the request and returns response

Router:
-------
Django REST Framework's DefaultRouter automatically creates URL patterns
for ViewSets. It generates the following URLs:

Standard CRUD URLs:
- GET    /api/users/              -> list all users
- POST   /api/users/              -> create new user
- GET    /api/users/{id}/         -> get specific user
- PUT    /api/users/{id}/         -> update user (full)
- PATCH  /api/users/{id}/         -> update user (partial)
- DELETE /api/users/{id}/         -> delete user

Custom Action URLs (from @action decorators):
- POST   /api/users/{id}/activate/     -> activate user
- POST   /api/users/{id}/deactivate/   -> deactivate user
- GET    /api/users/active_users/      -> get all active users
"""

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import UserViewSet

# Create a router instance
# DefaultRouter automatically generates URL patterns for ViewSets
router = DefaultRouter()

# Register the UserViewSet with the router
# Arguments:
# - 'users': The URL prefix for this viewset
# - UserViewSet: The viewset class to use
# - basename: Optional, used for URL name generation (auto-generated if not provided)
router.register(r'users', UserViewSet, basename='user')

# The router generates these URL patterns:
# ^users/$ 
#   - Name: 'user-list'
#   - Methods: GET (list), POST (create)
#
# ^users/(?P<pk>[^/.]+)/$ 
#   - Name: 'user-detail'
#   - Methods: GET (retrieve), PUT (update), PATCH (partial_update), DELETE (destroy)
#
# ^users/(?P<pk>[^/.]+)/activate/$ 
#   - Name: 'user-activate'
#   - Methods: POST
#
# ^users/(?P<pk>[^/.]+)/deactivate/$ 
#   - Name: 'user-deactivate'
#   - Methods: POST
#
# ^users/active_users/$ 
#   - Name: 'user-active-users'
#   - Methods: GET

# URL patterns for this app
urlpatterns = [
    # Include all router-generated URLs
    # This adds all the URLs generated by the router to this app's URL configuration
    path('', include(router.urls)),
]

# Alternative: If you want to add custom URLs alongside the router:
# urlpatterns = [
#     path('', include(router.urls)),
#     path('custom-endpoint/', custom_view, name='custom-endpoint'),
# ]

